config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :reservations do
      member do
        patch :approve, :refuse, :cancel, :arrive, :leave
      end
    end
    resources :room_types
    resources :rooms
    resources :rates
    resources :aggregations do
      collection do
        get :month, :day
      end
    end
  end

  root 'rooms#index'

  resources :reservations do
    member do
      patch :cancel
    end
    collection do
      get :search
    end
  end
  resources :room_types
  resources :rooms do
    member do
      post :prev, :next, :calc
    end
  end
  resources :contacts
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

#  get '*path', controller: 'application', action: 'render_404'
end

app/controllers/admin/room_types_controller.rb
class Admin::RoomTypesController < Admin::BaseController

  def index
    @room_types = RoomType.all
  end

  def show
    @room_type = RoomType.find(params[:id])
  end

  def new
    @room_type = RoomType.new
  end

  def create
    @room_type = RoomType.new(room_type_params)
    @room_type.save!
    redirect_to admin_room_types_url
  end

  def edit
    @room_type = RoomType.find(params[:id])
  end

  def update
    @room_type = RoomType.find(params[:id])
    @room_type.update!(room_type_params)
    redirect_to admin_room_types_url
  end

  def destroy
    @room_type = RoomType.find(params[:id])
    @room_type.destroy
    redirect_to admin_room_types_url
  end

  private
    def room_type_params
      params.require(:room_type).permit(:type_name, :capacity, :image, :room_note)
    end

end

app/controllers/room_types_controller.rb
class RoomTypesController < ApplicationController

  def index
    @room_types = RoomType.all.order(created_at: 'asc')
  end

  def show
    @room_type = RoomType.find(params[:id])
  end

end

app/helpers/admin/room_types_helper.rb
module Admin::RoomTypesHelper
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/views/admin/room_types/_form.html.erb
<div>
  <%= f.label :type_name, "客室タイプ名" %>
  <%= f.text_field :type_name %>
</div>
<div>
  <%= f.label :capacity, "定員数" %>
  <%= f.number_field :capacity %>
</div>
<div>
  <%= f.label :image, "画像" %>
  <%= f.file_field :image %>
</div>
<div>
  <%= f.label :room_note, "説明" %>
  <%= f.text_area :room_note %>
</div>

app/views/admin/room_types/edit.html.erb
<h2>客室タイプ編集</h2>

<div class="reserve_form">
  <%= form_for(@room_type, url: admin_room_type_path, method: :patch) do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit "設定を変更", class:"btn btn-primary",  data:{confirm: "設定を変更しますか？"} %>
  <% end %>
</div>

app/views/admin/room_types/index.html.erb
<h2>客室タイプ一覧</h2>
<div class="panel_area">

  <%= link_to "新規部屋タイプ作成", new_admin_room_type_path, method: :get, class: "btn btn-primary" %>

  <table>
    <thead>
      <tr>
        <th style="width: 260px;">客室タイプ名</th>
        <th style="width: 60px;">定員数</th>
        <th style="width: 60px;">客室数</th>
        <th>説明</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @room_types.each do |type| %>
      <tr>
        <td><%= type.type_name %></td>
        <td><%= type.capacity %>人</td>
        <td><%= Room.where(room_type_id: type.id).count %>室</td>
        <td><%= truncate(type.room_note, length: 36) %><%= link_to "詳細", admin_room_type_path(type.id) %></td>
        <td>

          <%= link_to "編集", edit_admin_room_type_path(type.id), class: "btn btn-xs btn-info" %>
          <%= link_to "客室を追加", new_admin_room_path(room_type_id: type.id), class: "btn btn-xs btn-success" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/room_types/new.html.erb
<h2>新規客室タイプ作成</h2>

<div class="reserve_form">
  <%= form_for(@room_type, url: admin_room_types_path, method: :post) do |f| %>
    <%= render 'form', f: f %>
      <%= f.submit "客室タイプを作成", class: "btn", data:{confirm: "客室タイプを作成しますか？"} %>
  <% end %>
</div>

app/views/admin/room_types/show.html.erb
<% provide(:title, @room_type.type_name) %>

<h2><%= @room_type.type_name %></h2>
<div class="room_detail">
  <div class="room_note">
  <p>定員数：<%= @room_type.capacity %>人</p>
  <%= @room_type.room_note %>
  </div>
  <div class="room_img">
  <% if @room_type.image? %>
    <%= image_tag @room_type.image.url %>
  <% else %>
    <div class="no_img">
      NO IMAGE
    </div>
  <% end %>
  </div>
</div>