config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :reservations do
      member do
        patch :approve, :refuse, :cancel, :arrive, :leave
      end
    end
    resources :room_types
    resources :rooms
    resources :rates
    resources :aggregations do
      collection do
        get :month, :day
      end
    end
  end

  root 'rooms#index'

  resources :reservations do
    member do
      patch :cancel
    end
    collection do
      get :search
    end
  end
  resources :room_types
  resources :rooms do
    member do
      post :prev, :next, :calc
    end
  end
  resources :contacts
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

#  get '*path', controller: 'application', action: 'render_404'
end

app/models/reservation.rb
class Reservation < ApplicationRecord

  enum status:{apply: 0, approve: 1, refuse: 2, cancel: 3, arrive: 4, leave: 5}

  validates :reserve_no, presence: true, uniqueness: true
  validates :guest_name, presence: true
  validates :guest_phone, presence: true, numericality: :true, length: { in: 10..15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :guest_mail, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :apply_date, presence: true
  validates :check_in_date, presence: true
  validates :check_out_date, presence: true
  validates :room_id, presence: true
  validates :guest_count, presence: true
  validates :status, presence: true
  validate :in_date_cannot_be_in_the_past
  validate :out_date_cannot_be_before_the_in_date
  validate :reserves_overlap

  def reserves_overlap
     reservations = Reservation.where(room_id: self.id).where('check_in_date <= ? AND ? <= check_out_date', self.check_out_date, self.check_in_date)
     reservations = reservations.where.not(id: self.id) if !self.new_record?

     errors.add(:check_in_date, "その期間はすでに予約が入っています") if reservations.any?
  end

  def in_date_cannot_be_in_the_past
    errors.add(:check_in_date, "申請日より前の日付は使用できません") if check_in_date < apply_date
  end

  def out_date_cannot_be_before_the_in_date
    errors.add(:check_out_date, "チェックイン日より前の日付は使用できません")  if check_out_date < check_in_date
  end

  def self.get_reserve(room_id, date)
    reserves = where(room_id: room_id)
    reserves.find_by('check_in_date <= ? AND check_out_date > ?', date, date)
  end

  def self.get_by_date(date)
    where('check_in_date <= ? AND check_out_date > ?', date, date)
  end

  def self.search(search)
    where('reserve_no = ?', search)
  end

  def self.date_check(room_id, in_date, out_date)
    where(room_id: room_id).where('check_in_date < ? AND ? < check_out_date', out_date, in_date)
  end

end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < Admin::BaseController
  before_action :authenticate_admin!

  def index
    @reservations = Reservation.all.order(created_at: :desc)
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def approve
    @reservation = Reservation.find(params[:id])
    if @reservation.apply?
       @reservation.approve!
       NotificationMailer.confirm_approve(@reservation).deliver_now
       Rails.logger.debug(params[:action])
       redirect_to admin_reservations_path
    end

  end

  def refuse
    @reservation = Reservation.find(params[:id])
    if @reservation.apply?
       @reservation.refuse!
       NotificationMailer.confirm_refuse(@reservation).deliver_now
       redirect_to admin_reservations_path
    end

  end

  def cancel
    @reservation = Reservation.find(params[:id])
    if @reservation.approve? or @reservation.arrive?
       @reservation.cancel!
       NotificationMailer.confirm_cancel(@reservation).deliver_now
       redirect_to admin_reservations_path
       flash[:tab_2] = true
    end

  end

  def arrive
    @reservation = Reservation.find(params[:id])
    if @reservation.approve?
       @reservation.arrive!
       redirect_to admin_reservations_path
       flash[:tab_2] = true
    end

  end


  def leave
    @tab_3 = true
    @reservation = Reservation.find(params[:id])
    if @reservation.arrive?
       @reservation.leave!
       redirect_to admin_reservations_path
       flash[:tab_3] = true
    end

  end


end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @reservation = Reservation.new
    @room_id = params[:reservation][:room_id]
    @guest_count = params[:reservation][:guest_count]
    @in_date = Date.parse(params[:reservation][:check_in_date])
    @out_date = Date.parse(params[:reservation][:check_out_date])
    @amount = params[:reservation][:amount]
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @room_id = params[:reservation][:room_id]
    @guest_count = params[:reservation][:guest_count]
    @in_date = Date.parse(params[:reservation][:check_in_date])
    @out_date = Date.parse(params[:reservation][:check_out_date])
    @amount = params[:reservation][:amount]

    if @reservation.save
      NotificationMailer.thanks_for_apply(@reservation).deliver_now
      NotificationMailer.confirm_apply(@reservation).deliver_now
      render 'create'
    else
      render 'new'
    end
  end

  def search
    @reservation = Reservation.search(params[:search])
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      flash[:success] ="予約内容を変更しました"
      redirect_to search_reservations_url
    else
      render 'edit'
    end
  end

  def cancel
    @reservation = Reservation.find(params[:id])
    if @reservation.approve? or @reservation.arrive?
       @reservation.cancel!
       NotificationMailer.confirm_cancel(@reservation).deliver_now
      flash[:success] ="予約をキャンセルしました"
       redirect_to search_reservations_url
    end
  end

  def destroy

  end

  private
    def reservation_params
      params.require(:reservation).permit(:reserve_no, :guest_name, :guest_mail, :guest_phone, :check_in_date, :check_out_date, :room_id, :guest_count, :stay_note, :status, :apply_date)
    end
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/admin/reservations/_list.html.erb
<table>
  <thead>
    <tr>
      <th style="width: 120px;">予約番号</th>
      <th style="width: 140px;">宿泊者名</th>
      <th style="width: 50px;">室名</th>
      <th style="width: 130px;">チェックイン日</th>
      <th style="width: 140px;">チェックアウト日</th>
      <th style="width: 90px;">ステータス</th>
      <th>予約編集</th>
    </tr>
  </thead>
  <tbody>
    <% reservations.each do |reserve| %>
    <tr>
      <td><%= reserve.reserve_no %></td>
      <td><%= reserve.guest_name %></td>
      <td><%= Room.find(reserve.room_id).room_name %></td>
      <td class="rsrv_in_date"><%= reserve.check_in_date %></td>
      <td><%= reserve.check_out_date %></td>
      <td><%= reserve.status_i18n %></td>
      <td>
        <%= render partial: "status_btn", locals:{reserve: reserve} %>
        <%= link_to "詳細", admin_reservation_path(reserve.id), method: :get, class: "btn btn-xs btn-default" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/reservations/_status_btn.html.erb
<% if reserve.apply? %>
  <%= button_to "承認", approve_admin_reservation_path(reserve.id), method: :patch, class: "btn btn-xs btn-info" %>
  <%= button_to "非承認", refuse_admin_reservation_path(reserve.id), method: :patch, class: "btn btn-xs btn-warning" %>
<% end %>
<% if reserve.approve? %>
  <%= button_to "受付", arrive_admin_reservation_path(reserve.id), method: :patch, class: "btn btn-xs btn-primary" %>
  <%= button_to "キャンセル", cancel_admin_reservation_path(reserve.id), method: :patch, class: "btn btn-xs btn-danger" %>
<% end %>
<% if reserve.arrive? %>
  <%= button_to "退去・支払", leave_admin_reservation_path(reserve.id), method: :patch, class: "btn btn-xs btn-success" %>
<% end %>

app/views/admin/reservations/index.html.erb
<h2>予約一覧</h2>

<% flash[:tab_1] = true if flash[:tab_2].blank? && flash[:tab_3].blank? %>

<%= radio_button_tag :tab, "1", flash[:tab_1] %>
<%= radio_button_tag :tab, "2", flash[:tab_2] %>
<%= radio_button_tag :tab, "3", flash[:tab_3] %>
<div class="tab_area">
  <%= label_tag :tab_1, "申請一覧", class: "tab1_label" %>
  <%= label_tag :tab_2, "承認一覧", class: "tab2_label" %>
  <%= label_tag :tab_3, "到着一覧", class: "tab3_label" %>
</div>

<div class="panel_area">
  <div id="apply_list" class="tab_panel">
    <% reservations = Reservation.where(status: 0) %>
    <%= render partial: 'list', locals:{reservations: reservations} %>
  </div>
  <div id="approve_list" class="tab_panel">
    <% reservations = Reservation.where(status: 1) %>
    <%= render partial: 'list', locals:{reservations: reservations} %>
  </div>
  <div id="arrive_list" class="tab_panel">
    <% reservations = Reservation.where(status: 4) %>
    <%= render partial: 'list', locals:{reservations: reservations} %>
  </div>
</div>

app/views/admin/reservations/show.html.erb
<h2>予約詳細</h2>
<% reserve = @reservation %>
<% duration = reserve.check_in_date..reserve.check_out_date.days_ago(1) %>
<% total = 0 %>
<% duration.each do |d| %>
  <% total += Rate.get_amount(Room.find(reserve.room_id).room_type, d).amount %>
<% end %>
<div>
  <dl>
    <dt>予約番号</dt>
    <dd><%= reserve.reserve_no %></dd>
    <dt>宿泊者名</dt>
    <dd><%= reserve.guest_name %></dd>
    <dt>メールアドレス</dt>
    <dd><%= reserve.guest_mail %></dd>
    <dt>電話番号</dt>
    <dd><%= reserve.guest_phone %></dd>
    <dt>備考</dt>
    <dd>
      <% if reserve.stay_note == nil %>
        <span>-</span>
      <% else %>
        <%= reserve.stay_note %>
      <% end %>
    </dd>
    <dt>客室名</dt>
    <dd><%= Room.find(reserve.room_id).room_name %></dd>
    <dt>客室タイプ</dt>
    <dd><%= Room.find(reserve.room_id).room_type.type_name %></dd>
    <dt>チェックイン日</dt>
    <dd><%= reserve.check_in_date %></dd>
    <dt>チェックアウト日</dt>
    <dd><%= reserve.check_out_date %></dd>
    <dt>泊数</dt>
    <dd><%= duration.count %>泊</dd>
    <dt>宿泊人数</dt>
    <dd><%= reserve.guest_count %></dd>
    <dt>宿泊料金</dt>
    <dd><%= total.to_s(:delimited) %>円</dd>
    <dt>ステータス</dt>
    <dd><%= reserve.status_i18n %></dd>
  </dl>
  <%= render partial: "status_btn", locals:{reserve: reserve} %>

  <%= link_to "一覧へ戻る", admin_reservations_path %>
</div>