config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :reservations do
      member do
        patch :approve, :refuse, :cancel, :arrive, :leave
      end
    end
    resources :room_types
    resources :rooms
    resources :rates
    resources :aggregations do
      collection do
        get :month, :day
      end
    end
  end

  root 'rooms#index'

  resources :reservations do
    member do
      patch :cancel
    end
    collection do
      get :search
    end
  end
  resources :room_types
  resources :rooms do
    member do
      post :prev, :next, :calc
    end
  end
  resources :contacts
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

#  get '*path', controller: 'application', action: 'render_404'
end

app/views/admin/_header.html.erb
<header>

    <%= link_to "Dashboard", admin_reservations_path, class: "logo" %>
    <nav>
      <ul class="menu">
        <li><%= link_to "予約管理", admin_reservations_path, method: :get %></li>
        <li><%= link_to "客室タイプ管理", admin_room_types_path, method: :get %></li>
        <li><%= link_to "宿泊料金管理", admin_rates_path, method: :get %></li>
        <li><%= link_to "売上集計管理", day_admin_aggregations_url, method: :get %>
          <ul>
            <li><%= link_to "月別売上集計", month_admin_aggregations_url, method: :get %></li>
            <li><%= link_to "日別売上集計", day_admin_aggregations_url, method: :get %></li>
          </ul>
        </li>
        <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
      </ul>
    </nav>

</header>