config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :reservations do
      member do
        patch :approve, :refuse, :cancel, :arrive, :leave
      end
    end
    resources :room_types
    resources :rooms
    resources :rates
    resources :aggregations do
      collection do
        get :month, :day
      end
    end
  end

  root 'rooms#index'

  resources :reservations do
    member do
      patch :cancel
    end
    collection do
      get :search
    end
  end
  resources :room_types
  resources :rooms do
    member do
      post :prev, :next, :calc
    end
  end
  resources :contacts
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

#  get '*path', controller: 'application', action: 'render_404'
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :room_type
  validates :rate_type, presence: true
  validates :amount, presence: true
  validates :rank, presence: true
  validates :room_type_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  def self.get_amount(room_type_id, date)
    rates = where(room_type_id: room_type_id).where('(start_date <= ? AND end_date >= ?)', date, date)

    if rates.where(weekday: date.wday).any?
      rates = rates.where(weekday: date.wday)
    else
      rates = rates.where(weekday: nil)
    end

    rank = rates.minimum('rank')
    rates.find_by(rank: rank)
  end


end

app/controllers/admin/rates_controller.rb
class Admin::RatesController < Admin::BaseController

  def index
    @rates = Rate.all
  end

  def new
    @rate = Rate.new
  end

  def create
    @rate = Rate.new(rate_params)
    if @rate.save
      redirect_to admin_rates_url
    end
  end

  def edit
    @rate = Rate.find(params[:id])
  end

  def update
    @rate = Rate.find(params[:id])
    @rate.update(rate_params)
    redirect_to admin_rates_url
  end

  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy
    redirect_to admin_rates_url
  end

  private
    def rate_params
      params.require(:rate).permit(:rate_type, :amount, :rank, :start_date, :end_date, :weekday, :room_type_id)
    end
end

app/helpers/admin/rates_helper.rb
module Admin::RatesHelper
end

app/views/admin/rates/_form.html.erb
<div>
  <%= f.label :rate_type, "料金プラン名" %>
  <%= f.text_field :rate_type %>
</div>
<div>
  <%= f.label :amount, "金額" %>
  <%= f.number_field :amount %>
</div>
<div>
  <%= f.label :room_type_id, "部屋タイプ" %>
  <%= f.collection_select :room_type_id, RoomType.all, :id, :type_name %>
</div>
<div>
  <%= f.label :start_date, "開始日" %>
  <%= f.date_field :start_date %>
</div>
<div>
  <%= f.label :end_date, "終了日" %>
  <%= f.date_field :end_date %>
</div>
<div>
  <%= f.label :weekday, "曜日" %>
  <%= f.select :weekday, [["選択しない", nil],["日曜日", "0"], ["月曜日", "1"], ["火曜日", "2"], ["水曜日", "3"], ["木曜日", "4"], ["金曜日", "5"], ["土曜日", "6"]] %>
</div>
<div>
  <%= f.label :rank, "優先順位" %>
  <%= f.select :rank, ["1", "2", "3", "4", "5"] %>
</div>

app/views/admin/rates/edit.html.erb
<h2>宿泊料金の変更</h2>

<div class="reserve_form">
  <%= form_for(@rate, url: admin_rates_path, method: :patch) do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit "宿泊料金を変更", class: "btn", data:{confirm: "この内容で変更しますか？"} %>
  <% end %>
  <%= link_to '料金一覧に戻る', admin_rates_url %>
</div>

app/views/admin/rates/index.html.erb
<h2>宿泊料金一覧</h2>


<div class="panel_area">
<%= link_to "新しい宿泊料金を追加", new_admin_rate_path, method: :get, class: "btn btn-primary" %>
  <table>
    <thead>
      <tr>
        <th>料金プラン名</th>
        <th>金額</th>
        <th>部屋タイプ</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>曜日</th>
        <th>優先順位</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @rates.each do |rate| %>
      <tr>
        <td><%= rate.rate_type %></td>
        <td><%= rate.amount %></td>
        <td><%= RoomType.find(rate.room_type_id).type_name %></td>
        <td><%= rate.start_date %></td>
        <td><%= rate.end_date %></td>
        <td><%= rate.weekday %></td>
        <td><%= rate.rank %></td>
        <td><%= link_to "編集", edit_admin_rate_path(rate.id), method: :get, class:"btn btn-xs btn-success" %></td>
        <td><%= link_to "削除", admin_rate_path(rate.id), method: :delete, class: "btn btn-xs btn-warning" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/rates/new.html.erb
<h2>新規宿泊料金作成</h2>

<div class="reserve_form">
  <%= form_for(@rate, url: admin_rates_path, method: :post) do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit "宿泊料金を作成", class: "btn", data:{confirm: "宿泊料金を作成しますか？"} %>
  <% end %>
</div>